function explore()
% EXPLORE - Main EEG Analysis GUI
% 5 tabs: Pre-processing, Wavelet Denoising, Adaptive Filtering,
%         Comparison, Merging
%
% Usage: explore()

fig = figure('Name','EEG Analysis Platform', ...
    'NumberTitle','off', ...
    'Color',[0.94 0.94 0.94], ...
    'Position',[80 80 1200 750], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'Resize','on');

%% ── Tab group ────────────────────────────────────────────────────────
tg = uitabgroup(fig, 'Units','normalized', 'Position',[0 0 1 1]);

tabNames = {'Pre-processing', 'Wavelet Denoising', ...
            'Adaptive Filtering', 'Comparison', 'Merging'};

tabs = gobjects(1, numel(tabNames));
for i = 1:numel(tabNames)
    tabs(i) = uitab(tg, 'Title', tabNames{i});
end

%% ══════════════════════════════════════════════════════════════════════
%  TAB 1 — Pre-processing (4-panel layout matching RTEEGAP)
%% ══════════════════════════════════════════════════════════════════════
t1 = tabs(1);

% Top-left: EEG Stream
uipanel(t1, 'Title','EEG-Stream', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0.45 0.64 0.55]);

% Bottom-left: FFT and Power
uipanel(t1, 'Title','FFT and Power', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0 0.32 0.44]);

% Bottom-middle: Topography
uipanel(t1, 'Title','Topography', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0.32 0 0.32 0.44]);

% Right: Controls
uipanel(t1, 'Title','Controls', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0.64 0 0.36 1.0]);

%% ══════════════════════════════════════════════════════════════════════
%  TAB 2 — Wavelet Denoising (empty for now)
%% ══════════════════════════════════════════════════════════════════════
uipanel(tabs(2), 'Title','Wavelet Denoising', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

%% ══════════════════════════════════════════════════════════════════════
%  TAB 3 — Adaptive Filtering (empty for now)
%% ══════════════════════════════════════════════════════════════════════
uipanel(tabs(3), 'Title','Adaptive Filtering', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

%% ══════════════════════════════════════════════════════════════════════
%  TAB 4 — Comparison (empty for now)
%% ══════════════════════════════════════════════════════════════════════
uipanel(tabs(4), 'Title','Comparison', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

%% ══════════════════════════════════════════════════════════════════════
%  TAB 5 — Merging (empty for now)
%% ══════════════════════════════════════════════════════════════════════
uipanel(tabs(5), 'Title','Merging', ...
    'FontWeight','bold', 'FontSize',10, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

end